name: build
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        ls -lA /usr/lib/gcc/x86_64-linux-gnu
        ls -lA /usr/include/c++
        # exit 1
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: ccache
      uses: hendrikmuhs/ccache-action@v1
    - uses: seanmiddleditch/gha-setup-ninja@master
    - name: Install Dependencies
      run: |
        sudo apt update && sudo apt install -y \
          cmake ninja-build libx11-dev libxcursor-dev libxi-dev libgl1-mesa-dev libfontconfig1-dev \
          libc++-10-dev libc++abi-10-dev libstdc++-10-dev clang-10 gcc-10 g++-10
        sudo apt upgrade -y
        mkdir skia
        wget -O skia.zip https://github.com/aseprite/skia/releases/latest/download/Skia-Linux-Release-x64-libc++.zip
        unzip -o -d skia skia.zip
    - name: Generating Makefiles
      run: |
        export CC=clang-10
        export CXX=clang++-10
        export CPLUS_INCLUDE_PATH=/usr/include/c++/10:/usr/include/x86_64-linux-gnu/c++/10
        cmake -S . -B build -G Ninja \
          -DCMAKE_BUILD_TYPE=RelWithDebInfo \
          -DCMAKE_CXX_FLAGS:STRING=-stdlib=libc++ \
          -DCMAKE_EXE_LINKER_FLAGS:STRING=-stdlib=libc++ \
          -DLAF_BACKEND=skia \
          -DSKIA_DIR=$PWD/skia \
          -DSKIA_LIBRARY_DIR=$PWD/skia/out/Release-x64 \
          -DSKIA_LIBRARY=$PWD/skia/out/Release-x64/libskia.a \
          -DENABLE_UI=on \
          -DENABLE_CCACHE=on \
          -DENABLE_TESTS=ON
    - name: Compiling
      run: cd build && ninja
    - name: Running C++ Tests
      run: cd build && xvfb-run ctest --output-on-failure
    - name: Running CLI Tests
      run: |
        cd build
        ls -lA bin
        git clone --branch main --recursive https://github.com/aseprite/tests.git
        cd tests
        ASEPRITE=$PWD/../bin/aseprite xvfb-run bash run-tests.sh
    - uses: actions/upload-artifact@v3
      name: "-"
      with:
        path: |
          build/bin/aseprite
          build/bin/data/
        if-no-files-found: error
        retention-days: 1
    - name: --
      run: exit 1
